### ISSUE TITLE
[question] Consume messages in batch mode

### ISSUE THREAD

**Issue by v9ru** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#122]
Common class
```
public class SomeEvent implements Serializable {
    private final long date;
    private final String event;
}
```

Producer
```
@Slf4j
@Component
class Producer {
    @Autowired
    private Source source;

    @Scheduled(fixedRate = 1000L)
    public void sendMessage() {
        SomeEvent data = new SomeEvent(1234, "event");
        source.output().send(MessageBuilder.withPayload(data).build());
        LOG.info("Produced: {}", data);
    }
}
```

Consumer

```
@Slf4j
@Component
public class Consumer {
    @StreamListener(Sink.INPUT)
    public void input(Message<SomeEvent> record) {
        LOG.info("consumed: {}", record.getPayload());
    }
}
```
In the above samples I used kinesis binder with listenerMode as `record` and I faced no issues.

I changed the listenerMode to `batch` and my consumer to below
```
@Slf4j
@Component
public class Consumer {
    @StreamListener(Sink.INPUT)
    public void input(Message<List<SomeEvent>> records) {
        List<SomeEvent> eventList = records.getPayload();
        for (SomeEvent event: eventList) {
            LOG.info("Consumed: {}", event);
        }
    }
}
```

and my configuration
```
spring:
  profiles: env-local

  cloud:
    stream:
      bindings:
        input:
          destination: nvivek-kinesis-binder-test
          group: nvivek-kinesis-binder-test-consumer
          content-type: application/json

      kinesis:
        binder:
          autoCreateStream: false
          kplKclEnabled: true

        bindings:
          input:
            consumer:
              startTimeout: 6000
              listenerMode: batch
              idleBetweenPolls: 1000
              consumerBackoff: 1000
              shardIteratorType: TRIM_HORIZON
```
Now I am getting the following error

```
org.springframework.messaging.MessagingException: Exception thrown while invoking Consumer#input[1 args]; nested exception is java.lang.ClassCastException: [B cannot be cast to com.indeed.spring.cloud.kinesis.binder.exp.models.SomeEvent, failedMessage=GenericMessage [payload=`a big list`, headers={aws_shard=shardId-000000000001, id=5cd11f9b-0f52-f064-dca7-31703569c035, contentType=application/json, aws_receivedPartitionKey=`a big list`, aws_receivedStream=nvivek-kinesis-binder-test, aws_receivedSequenceNumber=`a big list`, timestamp=1578930387442}]
	at org.springframework.cloud.stream.binding.StreamListenerMessageHandler.handleRequestMessage(StreamListenerMessageHandler.java:64)
	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:127)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:170)
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:115)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:133)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:106)
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:73)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:453)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:403)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47)
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109)
	at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:198)
	at org.springframework.integration.aws.inbound.kinesis.KclMessageDrivenChannelAdapter.access$1800(KclMessageDrivenChannelAdapter.java:82)
	at org.springframework.integration.aws.inbound.kinesis.KclMessageDrivenChannelAdapter$RecordProcessor.performSend(KclMessageDrivenChannelAdapter.java:499)
	at org.springframework.integration.aws.inbound.kinesis.KclMessageDrivenChannelAdapter$RecordProcessor.processMultipleRecords(KclMessageDrivenChannelAdapter.java:446)
	at org.springframework.integration.aws.inbound.kinesis.KclMessageDrivenChannelAdapter$RecordProcessor.processRecords(KclMessageDrivenChannelAdapter.java:403)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.V1ToV2RecordProcessorAdapter.processRecords(V1ToV2RecordProcessorAdapter.java:42)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ProcessTask.callProcessRecords(ProcessTask.java:221)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ProcessTask.call(ProcessTask.java:176)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:49)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:24)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassCastException: [B cannot be cast to com.indeed.spring.cloud.kinesis.binder.exp.models.SomeEvent
	at com.indeed.spring.cloud.kinesis.binder.exp.controllers.Consumer.input(Consumer.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:171)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:120)
	at org.springframework.cloud.stream.binding.StreamListenerMessageHandler.handleRequestMessage(StreamListenerMessageHandler.java:55)
	... 25 more
```

Am I missing something here? What should I give for content-type here?

**Comment by artembilan** [comment]
I wonder what is wrong with [docs on the matter](https://github.com/spring-cloud/spring-cloud-stream-binder-aws-kinesis/blob/master/spring-cloud-stream-binder-kinesis-docs/src/main/asciidoc/overview.adoc#kinesis-consumer-properties)...:

> `listenerMode`

>    The mode in which records are processed. If `record`, each `Message` will contain `byte[]` from a single `Record.data`. If `batch`, each Message will contain a `List<byte[]>` extracted from the consumed records. When `useNativeDecoding = true` is used on the consumer together with the `listenerMode = batch`, there is no any out-of-the-box conversion happened and a result message contains a payload like `List<com.amazonaws.services.kinesis.model.Record>`. It’s up to target application to convert those records manually.

>    Default: `record`

So, it states that when we use a `batch` mode, we have a `List<byte[]>`  as a `payload` in that message to consume in our `@StreamListener`. Therefore it's already up to you how to deal with that `List<byte[]>` in your code.

Do we need to improve something to make it much cleaner?

Thanks for understanding

**Comment by v9ru** [comment]
@artembilan Nope, that part is clear. But since it said for `record` you get each message as byte[] and naming it as `SomeEvent` worked I thought it can work with List<SomeEvent> too.

I have a different question though. How do I convert the byte[] to my object?

I tried https://stackoverflow.com/a/3736247/12487805 and it gave me an error and I read https://stackoverflow.com/a/23262382/12487805 and it says we need to know how it is converted to byte[]

Can you provide me with an example of how I can convert that to my object?

**Comment by artembilan** [comment]
Since you say that use `content-type: application/json` and your consumed `byte[]` is properly converted to a `SomeEvent`, then it sounds for me like a JSON conversion.
So, to convert every element in that `List<byte[]>` into its `SomeEvent` object you  need to inject a Jackson `ObjectMapper` into that your service and call its `readValue(data, SomeEvent.class)`.

**Comment by v9ru** [comment]
I changed my consumer to below
```
@Slf4j
@Component
public class Consumer {
    private static final ObjectMapper objectMapper = new ObjectMapper();

    @StreamListener(Sink.INPUT)
    public void input(Message<List<byte[]>> records) throws IOException {
        for(byte[] record: records.getPayload()) {
            SomeEvent event = objectMapper.readValue(record, SomeEvent.class);
            LOG.info("Consumed: {}", event);
        }
    }
}
```

I got the following error
```
org.springframework.messaging.MessagingException: Exception thrown while invoking Consumer#input[1 args]; nested exception is com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'ÿ': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (byte[])"�contentType"application/json"{"date":1234,"event":"abcde"}"; line: 1, column: 4]
```
I can see the data `{"date":1234,"event":"abcde"}` now but it is unable to parse it.
If possible can you point me to some example of consumers POJOs.

**Comment by artembilan** [comment]
That means that you produce records in the `embeddedHeaders` mode. Consider to configure it to `none` on the particular binding: https://cloud.spring.io/spring-cloud-static/spring-cloud-stream/3.0.1.RELEASE/reference/html/spring-cloud-stream.html#_producer_properties.
Since we deal with `batch` on the consumer side we don't need anything to do because Spring Cloud Stream doesn't deserialize `byte[]` for us any more.
but that won't hurt to configure a consumer side to use `none` for the `headerMode` as well.

You can consider to use an `EmbeddedHeaderUtils.extractHeaders()`, but then you need to wrap every `byte[]` element in that `List` into its own `Message` to satisfy contract.

**Comment by v9ru** [comment]
Thanks a lot, @artembilan.  Setting `headerMode` to none solved this for me.
