### ISSUE TITLE
How properly retry when an error occurs on sending an event

### ISSUE THREAD

**Issue by Kent1** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#123]
Hi,

I read that, since sending a Kinesis message is asynchronous, the kinesis binder was not using the retryTemplate from Spring-retry.

How then be sure that a message is send ? How to retry with some backoff to avoid internal error from Kinesis ?

To be more specific, i got errors yesterday evening (5 in a row, in an interval of 600ms):
```
org.springframework.integration.aws.support.AwsRequestFailureException: nested exception is com.amazonaws.services.kinesis.model.AmazonKinesisException: null (Service: AmazonKinesis; Status Code: 500; Error Code: InternalFailure; Request ID: f6b32b89-88c4-441b-a001-e9c2bd0b4ae4), failedMessage=GenericMessage [payload=byte[216], headers={contentType=application/json, id=d2d3bf74-c5d7-0db4-6fe9-85eef22372e2, timestamp=1580777477253}] [request={StreamName: my.stream.name,Data: java.nio.HeapByteBuffer[pos=0 lim=216 cap=216],PartitionKey: 904870202,}]
	at org.springframework.integration.aws.outbound.AbstractAwsMessageHandler$1.onError(AbstractAwsMessageHandler.java:214)
	at com.amazonaws.services.kinesis.AmazonKinesisAsyncClient$15.call(AmazonKinesisAsyncClient.java:991)
	at com.amazonaws.services.kinesis.AmazonKinesisAsyncClient$15.call(AmazonKinesisAsyncClient.java:982)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.amazonaws.services.kinesis.model.AmazonKinesisException: null (Service: AmazonKinesis; Status Code: 500; Error Code: InternalFailure; Request ID: f6b32b89-88c4-441b-a001-e9c2bd0b4ae4)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1638)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1303)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1055)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazonaws.services.kinesis.AmazonKinesisClient.doInvoke(AmazonKinesisClient.java:2219)
	at com.amazonaws.services.kinesis.AmazonKinesisClient.invoke(AmazonKinesisClient.java:2195)
	at com.amazonaws.services.kinesis.AmazonKinesisClient.executePutRecord(AmazonKinesisClient.java:1546)
	at com.amazonaws.services.kinesis.AmazonKinesisAsyncClient$15.call(AmazonKinesisAsyncClient.java:988)
	... 5 more
```

I have an error channel but i only log the error message.

```java
  @StreamListener("errorChannel")
  public void error(Message<?> message) {
    Object payload = message.getPayload();
    if (payload instanceof AwsRequestFailureException) {
      AwsRequestFailureException awsRequestFailureException = (AwsRequestFailureException) payload;
      Message<?> failedMessage = awsRequestFailureException.getFailedMessage();
      if (failedMessage != null) {
        logger.error("An exception occurred while sending an event: {}", failedMessage.getPayload());
      } else {
        logger.error("An exception occurred while sending an event");
      }
    } else {
      logger.error("Sending message failed: message = {}", message);
    }
  }
```

**Comment by artembilan** [comment]
You can consider to configure some common client configuration for AWS: https://aws.amazon.com/blogs/database/tuning-aws-java-sdk-http-request-settings-for-latency-aware-amazon-dynamodb-applications/

So, when you create a `AmazonKinesisAsync` bean, you can inject some `withClientConfiguration(ClientConfiguration)` and specify a `RetryPolicy` over there.

Since the publish is really an async from binder perspective it just does not make sense to apply Spring retry over there.

With that `errorChannel` logic implementation I would try to re-send `failedMessage` to the binding output channel.

**Comment by Kent1** [comment]
Thanks, i'll implement a retry in the AmazonKinesisAsync see how it behaves.

**Comment by nampoom** [comment]
@Kent1  - I had the same question and landed here. This is very useful information, could you please share the result of your experiment and if don't mind the retry implementation you have tried as well. Thanks for the help in advance.
