### ISSUE TITLE
Connection pool shut down

### ISSUE THREAD

**Issue by Kent1** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#139]
Hi,

I am sorry in advance if this issue is not really related to the kinesis binder.

I have the following issue: When the application is shutdown (restart of tomcat using systemd) i got sometimes the following exception : 

```
org.springframework.integration.aws.support.AwsRequestFailureException: nested exception is java.lang.IllegalStateException: Connection pool shut down, failedMessage=GenericMessage [payload=byte[170], headers={contentType=application/json, id=af421908-6bb7-1c1f-058a-06376601ebce, timestamp=1588927492124}] [request={StreamName: prod.registration.adrian.epp.query,Data: java.nio.HeapByteBuffer[pos=0 lim=170 cap=170],PartitionKey: 878150845,}]
	at org.springframework.integration.aws.outbound.AbstractAwsMessageHandler$1.onError(AbstractAwsMessageHandler.java:214)
	at com.amazonaws.services.kinesis.AmazonKinesisAsyncClient$20.call(AmazonKinesisAsyncClient.java:1157)
	at com.amazonaws.services.kinesis.AmazonKinesisAsyncClient$20.call(AmazonKinesisAsyncClient.java:1148)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Connection pool shut down
	at org.apache.http.util.Asserts.check(Asserts.java:34)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.requestConnection(PoolingHttpClientConnectionManager.java:269)
	at sun.reflect.GeneratedMethodAccessor140.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:76)
	at com.amazonaws.http.conn.$Proxy146.requestConnection(Unknown Source)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:176)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1323)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1139)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:796)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:764)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:738)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:698)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:680)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:544)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:524)
	at com.amazonaws.services.kinesis.AmazonKinesisClient.doInvoke(AmazonKinesisClient.java:2809)
	at com.amazonaws.services.kinesis.AmazonKinesisClient.invoke(AmazonKinesisClient.java:2776)
	at com.amazonaws.services.kinesis.AmazonKinesisClient.invoke(AmazonKinesisClient.java:2765)
	at com.amazonaws.services.kinesis.AmazonKinesisClient.executePutRecord(AmazonKinesisClient.java:2013)
	at com.amazonaws.services.kinesis.AmazonKinesisAsyncClient$20.call(AmazonKinesisAsyncClient.java:1154)
	... 5 more
```

I would like to be able to control the unbinding or at least, be aware when the connection pool gets closed.

Is that possible ?

Thanks,
Quentin

**Comment by artembilan** [comment]
Yes, it's probably better to ask AWS community on their channels.
Doesn't look like the concern apply for Spring.

I'm sorry we are not so familiar with low-level code of AWS SDK and how it interacts with Apache Commons HTTP Client.

Consider to raise a StackOverflow question.

**Comment by Kent1** [comment]
Thanks for the response. However, even though it is an aws stacktrace, spring handles the unbinding correct ?
That part is interesting to me, i woud like to control the unbinding so other beans get destroy before that happens and don't try to send message when the output binding is already closed.

**Comment by artembilan** [comment]
OK. That's sounds like an issue, but probably better to move it into https://github.com/spring-cloud/spring-cloud-stream since unbinding and the whole lifecycle control of bindings is performed over there.
You probably need to show some config to determine what components you have which continue to emit messages to that outbound binding which looks like is closed earlier than producer in your applicaiton.
