### ISSUE TITLE
Control bean destruction and unbinding

### ISSUE THREAD

**Issue by Kent1** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#140]
Hi all,

Sorry for creating an issue but cannot see if it is a bug or me just doing something wrong.

**Short summary**

I have an app where i send messages to Kinesis with the kinesis binder.

The _eppCommandProcessor_ call the _logEvent_ method of the _CloudStreamEppEventService_ to send events to Kinesis.
My problem is that, when stopping tomcat (every time we deploy), we sometimes have an error because the eppCommandProcessor try to log an event while the binding is already closed.

Is there a way to control the unbinding and the bean destruction ?

**Stacktrace**

```
org.springframework.integration.aws.support.AwsRequestFailureException: nested exception is java.lang.IllegalStateException: Connection pool shut down, failedMessage=GenericMessage [payload=byte[170], headers={contentType=application/json, id=af421908-6bb7-1c1f-058a-06376601ebce, timestamp=1588927492124}] [request={StreamName: prod.registration.adrian.epp.query,Data: java.nio.HeapByteBuffer[pos=0 lim=170 cap=170],PartitionKey: 878150845,}]
	at org.springframework.integration.aws.outbound.AbstractAwsMessageHandler$1.onError(AbstractAwsMessageHandler.java:214)
	at com.amazonaws.services.kinesis.AmazonKinesisAsyncClient$20.call(AmazonKinesisAsyncClient.java:1157)
	at com.amazonaws.services.kinesis.AmazonKinesisAsyncClient$20.call(AmazonKinesisAsyncClient.java:1148)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Connection pool shut down
	at org.apache.http.util.Asserts.check(Asserts.java:34)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.requestConnection(PoolingHttpClientConnectionManager.java:269)
	at sun.reflect.GeneratedMethodAccessor140.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:76)
	at com.amazonaws.http.conn.$Proxy146.requestConnection(Unknown Source)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:176)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1323)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1139)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:796)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:764)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:738)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:698)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:680)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:544)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:524)
	at com.amazonaws.services.kinesis.AmazonKinesisClient.doInvoke(AmazonKinesisClient.java:2809)
	at com.amazonaws.services.kinesis.AmazonKinesisClient.invoke(AmazonKinesisClient.java:2776)
	at com.amazonaws.services.kinesis.AmazonKinesisClient.invoke(AmazonKinesisClient.java:2765)
	at com.amazonaws.services.kinesis.AmazonKinesisClient.executePutRecord(AmazonKinesisClient.java:2013)
	at com.amazonaws.services.kinesis.AmazonKinesisAsyncClient$20.call(AmazonKinesisAsyncClient.java:1154)
	... 5 more 
```

**Code**

EppCommandProcessor

```java
public class EppCommandProcessor implements IEppCommandProcessor {

  private static final Logger logger = LoggerFactory.getLogger(EppCommandProcessor.class);
  private static final Logger txLogger = LoggerFactory.getLogger("txLogger");

  private CommunicationDAO communicationDAO;

  private DomainHandler domainHandler;

  private ContactHandler contactHandler;

  private NsgroupHandler nsgroupHandler;

  private KeygroupHandler keygroupHandler;

  private RegistrarHandler registrarHandler;

  private AbuseService abuseService;

  private DomainCreateHandler domainCreateHandler;

  private UpdateDomainHandler updateDomainHandler;

  private PollHandler pollHandler;

  private EppQuotaManager eppQuotaManager;

  @Autowired
  private EppEventService eppEventService;

...
```

We start the transition from spring framework to Spring boot, so the bean definition is a mix of xml + componentscan (as far as i know, there is no way to use SCS with xml, right ?)

```xml
  <!-- This proxy wraps the service methods in transactions  -->
  <bean id="eppService" class="be.dns.epp.EppService" init-method="init">
    <property name="dataSource" ref="dataSource"/>
    <property name="domainDAO" ref="domainDAO"/>
    <property name="agentDAO" ref="agentDAO"/>
    <property name="contactDAO" ref="contactDAO"/>
    <property name="monitoredContactDAO" ref="monitoredContactDAO"/>
    <property name="nsgroupDAO" ref="nsgroupDAO"/>
    <property name="keygroupDAO" ref="keygroupDAO"/>
    <property name="transferDAO" ref="transferDAO"/>
    <property name="registrationDAO" ref="registrationDAO"/>
    <property name="abusePointDAO" ref="abusePointDAO"/>
    <property name="registrationService" ref="registrationService"/>
    <property name="whitelistedSubnets" value="${epp.whitelisted_subnets}"/>
  </bean>
```

```java
package be.dns.epp.event;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.cloud.stream.annotation.EnableBinding;
import org.springframework.cloud.stream.annotation.StreamListener;
import org.springframework.cloud.stream.messaging.Source;
import org.springframework.integration.aws.support.AwsRequestFailureException;
import org.springframework.messaging.Message;
import org.springframework.messaging.support.MessageBuilder;
import org.springframework.stereotype.Component;

import javax.annotation.PreDestroy;

@Component
@EnableBinding(Source.class)
@ConditionalOnProperty(value = "epp.event.enabled")
public class CloudStreamEppEventService implements EppEventService {

  private static final Logger logger = LoggerFactory.getLogger(CloudStreamEppEventService.class);

  private final Source source;

  private final ObjectMapper objectMapper = new ObjectMapper();

  public CloudStreamEppEventService(Source source) {
    logger.info("Creating CloudStreamEppEventService");
    this.source = source;
  }

  @Override
  public void logEvent(EppEvent eppEvent) {
    if (eppEvent == null) {
      logger.warn("trying to log null event");
    } else if (eppEvent.getType() == null) {
      logger.debug("Not logging events with no query type");
    } else {
      try {
        logger.debug("Sending epp event {}", objectMapper.writeValueAsString(MessageBuilder.withPayload(eppEvent).build()));
        source.output().send(MessageBuilder.withPayload(eppEvent).build());
      } catch (Exception exception) {
        logger.error("Not able to send event {}", eppEvent);
      }
    }
  }

  @StreamListener("errorChannel")
  public void error(Message<?> message) {
    Object payload = message.getPayload();
    if (payload instanceof AwsRequestFailureException) {
      AwsRequestFailureException awsRequestFailureException = (AwsRequestFailureException) payload;
      Message<?> failedMessage = awsRequestFailureException.getFailedMessage();
      if (failedMessage != null) {
        logger.error("An exception occurred while sending an event: {}", failedMessage.getPayload());
      } else {
        logger.error("An exception occurred while sending an event");
      }
    } else {
      logger.error("Sending message failed: message = {}", message);
    }
  }
  
}

```

Spring boot 2.2.8.RELEASE
SCS 3.0.4.RELEASE
spring-cloud-stream-binder-kinesis 2.0.1.RELEASE

**Comment by artembilan** [comment]
Who calls that `public void logEvent(EppEvent eppEvent) {`?
Can that one implement a `SmartLifecycle` and stop to produce events when it is not in the `running` state?
I'm not sure what the bug you try to report here, but it doesn't look like the framework is in the control of your `EppCommandProcessor`...

**Comment by Kent1** [comment]
Thanks for the reply ! When you say not in the control of the framework, you mean spring framework ?
It is indeed eppCommandProcessor who calls the log event. It is a bean registered in spring so I would assume the bean is destroyed before CloudStreamEppEventService since there is a dependency ?
I'll have a look to the SmartLifecycle, I have no experience with that.

**Comment by artembilan** [comment]
Right. Show, please, the code for that `eppCommandProcessor`. I'd like to understand how it calls that `logEvent()`. What is the trigger for it

**Comment by Kent1** [comment]
```java
package be.dns.epp;

import be.dns.adrian.common.Agent;
import be.dns.adrian.common.Communication;
import be.dns.adrian.dao.CommunicationDAO;
import be.dns.adrian.service.AbuseService;
import be.dns.adrian.transactions.Result;
import be.dns.epp.event.EppEvent;
import be.dns.epp.event.EppEventService;
import com.jamonapi.Monitor;
import com.jamonapi.MonitorFactory;
import org.apache.commons.lang3.StringUtils;
import org.joda.time.DateTime;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Required;
import org.springframework.transaction.TransactionException;
import org.springframework.transaction.annotation.Transactional;
import x0.ietfParamsXmlNsEpp1.PollOpType;
import x0.ietfParamsXmlNsEpp1.TransferOpType;

import javax.annotation.PreDestroy;
import java.io.IOException;
import java.time.Instant;
import java.util.Date;

public class EppCommandProcessor implements IEppCommandProcessor {

  private static final Logger logger = LoggerFactory.getLogger(EppCommandProcessor.class);
  private static final Logger txLogger = LoggerFactory.getLogger("txLogger");

  private CommunicationDAO communicationDAO;

  private DomainHandler domainHandler;

  private ContactHandler contactHandler;

  private NsgroupHandler nsgroupHandler;

  private KeygroupHandler keygroupHandler;

  private RegistrarHandler registrarHandler;

  private AbuseService abuseService;

  private DomainCreateHandler domainCreateHandler;

  private UpdateDomainHandler updateDomainHandler;

  private PollHandler pollHandler;

  private EppQuotaManager eppQuotaManager;

  @Autowired
  private EppEventService eppEventService;

  public void setCommunicationDAO(CommunicationDAO communicationDAO) {
    this.communicationDAO = communicationDAO;
  }

  public void setDomainHandler(DomainHandler domainHandler) {
    this.domainHandler = domainHandler;
  }

  public void setContactHandler(ContactHandler contactHandler) {
    this.contactHandler = contactHandler;
  }

  public void setNsgroupHandler(NsgroupHandler nsgroupHandler) {
    this.nsgroupHandler = nsgroupHandler;
  }

  public void setKeygroupHandler(KeygroupHandler keygroupHandler) {
    this.keygroupHandler = keygroupHandler;
  }

  public void setRegistrarHandler(RegistrarHandler registrarHandler) {
    this.registrarHandler = registrarHandler;
  }

  public void setDomainCreateHandler(DomainCreateHandler domainCreateHandler) {
    this.domainCreateHandler = domainCreateHandler;
  }

  public void setUpdateDomainHandler(UpdateDomainHandler updateDomainHandler) {
    this.updateDomainHandler = updateDomainHandler;
  }

  public void setPollHandler(PollHandler pollHandler) {
    this.pollHandler = pollHandler;
  }

  public void setAbuseService(AbuseService abuseService) {
    this.abuseService = abuseService;
  }

  @Required
  public void setEppQuotaManager(EppQuotaManager eppQuotaManager) {
    this.eppQuotaManager = eppQuotaManager;
  }

  public void setEppEventService(EppEventService eppEventService) {
    this.eppEventService = eppEventService;
  }

  private void checkAbuse(EppSession session, Communication communication, Reply reply) {
    if (communication != null) {
      int code = reply.getCommunication().getStatus();
      if (code != Result.SUCCESS.code() && code != Result.SUCCESS_ENDING_SESSION.code()) {
        logger.info("command failed: code={} => update abuse counters", code);
        abuseService.registerAbuse(communication, session.getAgent());
      }
    }
  }

  @Transactional
  public void processCommand(EppSession session, Request request, Reply reply) throws IOException {
    Communication communication = null;
    boolean createCommunication = request.shouldStore();
    if (createCommunication) {
      Agent agent = session.getAgent();
      String textIn = request.getTextIn();
      communication = new Communication();
      communication.setAgent(agent);
      communication.getText().setTextin(textIn);
      communication.setCreateEpoch(new Date());
      communication.setCreateWho("EPP:" + agent.getAgentId());
      communication.setObjectType(request.getObjectType());
      storeCommIn(communication);
      reply.setCommunication(communication);
      reply.setSvTRID(communication.getId());
    }
    logger.debug("Checking command type ...");
    if (eppQuotaManager.canProceed(new DateTime(), session, request, reply)) {
      doProcessCommand(session, request, reply);
      checkAbuse(session, communication, reply);
    }
    storeCommOut(reply);
  }

  private void doProcessCommand(EppSession session, Request request, Reply reply) {
    if (request.isDomainCreate()) {
      request.setTag(Request.Tag.DOMAIN_CREATE);
      Monitor monitor = MonitorFactory.start("EppCommandProcessor.domainCreate");
      try {
        domainCreateHandler.processDomainCreate(session, request, reply);
      } finally {
        monitor.stop();
      }
      return;
    }
    if (request.isContactCreate()) {
      request.setTag(Request.Tag.CONTACT_CREATE);
      contactHandler.processContactCreate(session, request, reply);
      return;
    }
    if (request.isContactUpdate()) {
      request.setTag(Request.Tag.CONTACT_UPDATE);
      contactHandler.processContactUpdate(session, request, reply);
      return;
    }
    if (request.isContactDelete()) {
      request.setTag(Request.Tag.CONTACT_DELETE);
      contactHandler.processContactDelete(session, request, reply);
      return;
    }
    if (request.isContactInfo()) {
      request.setTag(Request.Tag.CONTACT_INFO);
      contactHandler.processContactInfo(session, request, reply);
      boolean requestHasAuthInfo = request.getContactInfo().isSetAuthInfo()
          && request.getContactInfo().getAuthInfo().isSetPw()
          && StringUtils.isNotEmpty(request.getContactInfo().getAuthInfo().getPw().getStringValue());

      eppEventService.logEvent(new EppEvent(Instant.now(), session.getAgent().getAgentId(), requestHasAuthInfo,
          Request.Tag.CONTACT_INFO,"be", request.getContactInfo().getId(), reply.getResult()));
      return;
    }
    if (request.isNsgroupCreate()) {
      request.setTag(Request.Tag.NSGROUP_CREATE);
      nsgroupHandler.processNsgroupCreate(session, request, reply);
      return;
    }
    if (request.isNsgroupUpdate()) {
      request.setTag(Request.Tag.NSGROUP_UPDATE);
      nsgroupHandler.processNsgroupUpdate(session, request, reply);
      return;
    }
    if (request.isNsgroupInfo()) {
      request.setTag(Request.Tag.NSGROUP_INFO);
      nsgroupHandler.processNsgroupInfo(session, request, reply);
      return;
    }
    if (request.isNsgroupCheck()) {
      request.setTag(Request.Tag.NSGROUP_CHECK);
      nsgroupHandler.processNsgroupCheck(session, request, reply);
      return;
    }
    if (request.isNsgroupDelete()) {
      request.setTag(Request.Tag.NSGROUP_DELETE);
      nsgroupHandler.processNsgroupDelete(session, request, reply);
      return;
    }
    if (request.isKeygroupCreate()) {
      request.setTag(Request.Tag.KEYGROUP_CREATE);
      keygroupHandler.processKeygroupCreate(session, request, reply);
      return;
    }
    if (request.isKeygroupUpdate()) {
      request.setTag(Request.Tag.KEYGROUP_UPDATE);
      keygroupHandler.processKeygroupUpdate(session, request, reply);
      return;
    }
    if (request.isKeygroupInfo()) {
      request.setTag(Request.Tag.KEYGROUP_INFO);
      keygroupHandler.processKeygroupInfo(session, request, reply);
      return;
    }
    if (request.isKeygroupCheck()) {
      request.setTag(Request.Tag.KEYGROUP_CHECK);
      keygroupHandler.processKeygroupCheck(session, request, reply);
      return;
    }
    if (request.isKeygroupDelete()) {
      request.setTag(Request.Tag.KEYGROUP_DELETE);
      keygroupHandler.processKeygroupDelete(session, request, reply);
      return;
    }
    if (request.isDomainUpdate()) {
      request.setTag(Request.Tag.DOMAIN_UPDATE);
      updateDomainHandler.processDomainUpdate(session, request, reply);
      return;
    }
    if (request.isDomainDelete()) {
      request.setTag(Request.Tag.DOMAIN_DELETE);
      domainHandler.processDomainDelete(session, request, reply);
      return;
    }
    if (request.isDomainUndelete()) {
      request.setTag(Request.Tag.DOMAIN_UNDELETE);
      domainHandler.processDomainUndelete(session, request, reply);
      return;
    }
    if (request.isDomainReactivate()) {
      request.setTag(Request.Tag.DOMAIN_REACTIVATE);
      domainHandler.processDomainReactivate(session, request, reply);
      return;
    }
    if (request.isDomainCheck()) {
      request.setTag(Request.Tag.DOMAIN_CHECK);
      domainHandler.processDomainCheck(request, reply);
      eppEventService.logEvent(new EppEvent(Instant.now(), session.getAgent().getAgentId(), false,
          Request.Tag.DOMAIN_CHECK,"be", request.getDomainCheck().getNameArray(), reply.getResult()));
      return;
    }
    if (request.isDomainInfo()) {
      request.setTag(Request.Tag.DOMAIN_INFO);
      domainHandler.processDomainInfo(session, request, reply);

      boolean requestHasAuthCode = request.getDomainInfo().getAuthInfo() != null
          && request.getDomainInfo().getAuthInfo().getPw() != null
          && StringUtils.isNotEmpty(request.getDomainInfo().getAuthInfo().getPw().getStringValue());

      eppEventService.logEvent(new EppEvent(Instant.now(), session.getAgent().getAgentId(), requestHasAuthCode,
          Request.Tag.DOMAIN_INFO,"be", request.getDomainInfo().getName().getStringValue(), reply.getResult()));
      return;
    }
    if (request.isDomainTransfer()) {
      request.setTag(Request.Tag.DOMAIN_TRANSFER);
      TransferOpType.Enum opType = request.getDomainTransferOpType();
      if (opType.equals(TransferOpType.REQUEST)) {
        domainHandler.processDomainTransfer(session, request, reply);
      } else {
        logger.debug("unimplemented command option");
        reply.setResult(Result.UNIMPLEMENTED_OPTION);
      }
      return;
    }
    if (request.isRequestAuthCode()) {
      request.setTag(Request.Tag.REQUEST_AUTH_CODE);
      domainHandler.processAuthCodeRequest(session, request, reply);
      return;
    }
    if (request.isRegistrarInfo()) {
      request.setTag(Request.Tag.REGISTRAR_INFO);
      registrarHandler.processRegistrarInfo(session, request, reply);
      return;
    }
    if (request.isPoll()) {
      if (request.getPollOp() == PollOpType.REQ) {
        request.setTag(Request.Tag.POLL_REQUEST);
      }
      if (request.getPollOp() == PollOpType.ACK) {
        request.setTag(Request.Tag.POLL_ACK);
      }
      pollHandler.processPoll(session, request, reply);
      return;
    }
    logger.debug("unimplemented command ");
    reply.setResult(Result.UNIMPLEMENTED_COMMAND);
  }

  private void storeCommIn(Communication communication) {
    try {
      communicationDAO.insertCommunication(communication);
    } catch (TransactionException e) {
      logger.error("storeCommIn failed", e);
      throw e;
    }
  }

  private void storeCommOut(Reply reply) {
    if (reply.getCommunication() != null) {
      String textOut = reply.getText();
      reply.getCommunication().getText().setTextout(textOut);
      Monitor monitorStoreCommOut = MonitorFactory.start("storeCommOut");
      logTransaction(reply);
      try {
        communicationDAO.updateCommunication(reply.getCommunication());
        communicationDAO.insertCommunicationTexts(reply.getCommunication());
      } catch (TransactionException e) {
        logger.error("storeCommOut failed", e);
        throw e;
      }
      monitorStoreCommOut.stop();
    }
  }

  private void logTransaction(Reply reply) {
    txLogger.info("{} -> ({}, {}, C:{}, {}, {})",
        new Object[]{reply.getCommunication().getCreateWho(), reply.getCommunication().getActionTypeAsString(),
            reply.getCommunication().getObject(), reply.getCommunication().getId(),
            reply.getCommunication().getStatus(), reply.getMessage()});
  }

  @PreDestroy
  public void destroy() {
    logger.info("Destroying EppCommandProcessor");
  }

}
```

**Comment by artembilan** [comment]
> Our app uses Netty to handle epp protocol which is xml based protocol.

That's fully out of Spring Cloud Stream control.
You should consider to configure that Netty event loop to stop producing when your Tomcat is stopped.
Have no idea how to do that.
The output binding in Spring Cloud Stream is stopped because the Spring application context is stopped by the respective Tomcat event. At the same time it looks like your Netty endpoint is not stopped properly.

Not sure what you are looking for here in Spring Cloud Stream support. More over it is far away from Kinesis...

Please, be more specific in the future when you raise issues. Fully not clear why you blame Kinesis Binder all the time...

**Comment by Kent1** [comment]
i don't blame kinesis binder at all .. I did not move this issue from Spring Cloud stream repo to the kinesis binder .. I only see that now and i don't agree with it.

Like i said, to repeat myself, i don't blame any product, i wanted to know if there was a way to control the bean destruction and the unbinding of the source output. And optionally, understand why it does not work out of the box.

You always do software using only one lib ? The fact that i use Netty should not raise an issue here, it is a bean for Spring.
I do stop the Netty server at a @Predestroy, so my question remains the same, why the EppCloudStreamEventService is destroyed before ? Shouldn't it wait for the NettyEppServer being actually destroyed ?

Here's the code of the NettyEppServer.

```java
@Component
public class NettyEppServer {

  private final int port;
  private static final Logger logger = LoggerFactory.getLogger(NettyEppServer.class);
  private ServerStatus status = ServerStatus.STOPPED;
  private Channel serverChannel;
  private EventLoopGroup bossGroup;
  private EventLoopGroup workerGroup;
  private EppChannelInitializer channelInitializer;
  private final ServerHistory serverHistory;

  private final List<String> protocols;
  private final List<String> ciphers;

  @Autowired
  public NettyEppServer(@Value("${epp.netty.port}") Integer port,
                        @Value("${epp.protocols}") String protocolsString,
                        @Value("${epp.ciphers}") String ciphersString,
                        EppChannelInitializer channelInitializer,
                        ServerHistory serverHistory) {
    this.port = port;
    this.channelInitializer = channelInitializer;
    this.protocols = Arrays.asList(protocolsString.split(","));
    this.ciphers = Arrays.asList(ciphersString.split(","));
    this.serverHistory = serverHistory;
  }

  @PostConstruct
  public synchronized void run() {
    if (status != ServerStatus.STOPPED) {
      throw new RuntimeException("Unable to start an active server");
    }
    SocketAddress socketAddress = new InetSocketAddress("0.0.0.0", port);
    serverHistory.addEvent("startup requested at " + socketAddress);

    bossGroup = new NioEventLoopGroup();
    workerGroup = new NioEventLoopGroup();

    try {
      status = ServerStatus.STARTING;
      ServerBootstrap bootstrap = new ServerBootstrap();
      bootstrap.group(bossGroup, workerGroup)
              .channel(NioServerSocketChannel.class)
              .childHandler(channelInitializer)
              .option(ChannelOption.SO_BACKLOG, 128)
              .childOption(ChannelOption.SO_KEEPALIVE, true);

      serverChannel = bootstrap.bind(port).sync().channel();
      logger.info("Epp server started");
      status = ServerStatus.RUNNING;

      logProtocolsAndCiphers(protocols, ciphers);
      serverHistory.addEvent("startup succeeded");
    } catch (Exception e) {
      logger.error("Server not started", e);
      workerGroup.shutdownGracefully();
      bossGroup.shutdownGracefully();
      status = ServerStatus.STOPPED;
    }
  }

  @PreDestroy
  public synchronized void shutdown() {
    if (status != ServerStatus.RUNNING) {
      throw new RuntimeException("Unable to stop a not RUNNING server");
    }

    status = ServerStatus.STOPPING;
    try {
      serverChannel.close();
      workerGroup.shutdownGracefully();
      bossGroup.shutdownGracefully();
    } finally {
      status = ServerStatus.STOPPED;
    }
  }
}
```

Btw, thank you for your help, it is appreciated.

**Comment by Kent1** [comment]
i don't blame kinesis binder at all .. I did not move this issue from Spring Cloud stream repo to the kinesis binder .. I only see that now and i don't agree with it.

Like i said, to repeat myself, i don't blame any product, i wanted to know if there was a way to control the bean destruction and the unbinding of the source output. And optionally, understand why it does not work out of the box.

You always build software using only one lib ? The fact that i use Netty should not raise an issue here, it is a bean for Spring.
I do stop the Netty server at a @Predestroy, so my question remains the same, why the EppCloudStreamEventService is destroyed before ?

Here's the code of the NettyEppServer.

```java
@Component
public class NettyEppServer {

  private final int port;
  private static final Logger logger = LoggerFactory.getLogger(NettyEppServer.class);
  private ServerStatus status = ServerStatus.STOPPED;
  private Channel serverChannel;
  private EventLoopGroup bossGroup;
  private EventLoopGroup workerGroup;
  private EppChannelInitializer channelInitializer;
  private final ServerHistory serverHistory;

  private final List<String> protocols;
  private final List<String> ciphers;

  @Autowired
  public NettyEppServer(@Value("${epp.netty.port}") Integer port,
                        @Value("${epp.protocols}") String protocolsString,
                        @Value("${epp.ciphers}") String ciphersString,
                        EppChannelInitializer channelInitializer,
                        ServerHistory serverHistory) {
    this.port = port;
    this.channelInitializer = channelInitializer;
    this.protocols = Arrays.asList(protocolsString.split(","));
    this.ciphers = Arrays.asList(ciphersString.split(","));
    this.serverHistory = serverHistory;
  }

  @PostConstruct
  public synchronized void run() {
    if (status != ServerStatus.STOPPED) {
      throw new RuntimeException("Unable to start an active server");
    }
    SocketAddress socketAddress = new InetSocketAddress("0.0.0.0", port);
    serverHistory.addEvent("startup requested at " + socketAddress);

    bossGroup = new NioEventLoopGroup();
    workerGroup = new NioEventLoopGroup();

    try {
      status = ServerStatus.STARTING;
      ServerBootstrap bootstrap = new ServerBootstrap();
      bootstrap.group(bossGroup, workerGroup)
              .channel(NioServerSocketChannel.class)
              .childHandler(channelInitializer)
              .option(ChannelOption.SO_BACKLOG, 128)
              .childOption(ChannelOption.SO_KEEPALIVE, true);

      serverChannel = bootstrap.bind(port).sync().channel();
      logger.info("Epp server started");
      status = ServerStatus.RUNNING;

      logProtocolsAndCiphers(protocols, ciphers);
      serverHistory.addEvent("startup succeeded");
    } catch (Exception e) {
      logger.error("Server not started", e);
      workerGroup.shutdownGracefully();
      bossGroup.shutdownGracefully();
      status = ServerStatus.STOPPED;
    }
  }

  @PreDestroy
  public synchronized void shutdown() {
    if (status != ServerStatus.RUNNING) {
      throw new RuntimeException("Unable to stop a not RUNNING server");
    }

    status = ServerStatus.STOPPING;
    try {
      serverChannel.close();
      workerGroup.shutdownGracefully();
      bossGroup.shutdownGracefully();
    } finally {
      status = ServerStatus.STOPPED;
    }
  }
}
```

The bean dependencies looks like that
NettyEppServer -> EppChannelInitializer -> EppNetHandler -> EppService -> EppExecutor -> EppCommandProcessor -> EppCloudStreamEventService.

I can confirm that i see (locally, i run more test now on aws) the following logging:

```
2020-07-06 09:33:08,566 [SpringContextShutdownHook] INFO                    be.dnsbelgium.epp.NettyEppServer -                                         - Shutting Down NettyEppServer
2020-07-06 09:33:08,569 [SpringContextShutdownHook] INFO             be.dnsbelgium.epp.EppChannelInitializer -                                         - Destroying EppChannelInitializer
2020-07-06 09:33:08,570 [SpringContextShutdownHook] INFO                     be.dnsbelgium.epp.EppNetHandler -                                         - Destroying EppNetHandler
2020-07-06 09:33:08,570 [SpringContextShutdownHook] INFO                    be.dnsbelgium.epp.EppServiceImpl -                                         - Destroying EppService
2020-07-06 09:33:08,570 [SpringContextShutdownHook] INFO                              be.dns.epp.EppExecutor -                                         - Destroying EppExecutor
2020-07-06 09:33:08,570 [SpringContextShutdownHook] INFO                      be.dns.epp.EppCommandProcessor -                                         - Destroying EppCommandProcessor
```

Btw, thank you for your help, it is appreciated.

**Comment by Kent1** [comment]
Now that i pay attention to those predestroy methods, i see that the shutdown of the netty server is asynchronous. I guess that could explain the behaviour. I try to make the graceful shutdown of the netty server and see if that still happens. I close the issue for now, thanks for your help !

**Comment by Kent1** [comment]
I did make the netty server synchronously shutting down but that was not the root cause.
I see in the logs that the error happens before all @predestroy's. So i am still wondering why the connection pool is closed before, and what triggers that.

**Comment by artembilan** [comment]
I think  `@PreDestroy` is a bit late for such a logic: the bindings have been already stopped.

Consider to implement a `SmartLifecycle` and do that `shutdown()` logic in the `stop()` implementation.
