### ISSUE TITLE
Exception: Security Token included in the request is invalid

### ISSUE THREAD

**Issue by pavankumarchaitanya** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#19]
Hi,

I'm trying to connect to Kinesis from my dev machine to AWS. 

I have set up the ~/.aws/credentials file and also have set system properties as 
```
System.setProperty("AWS_ACCESS_KEY_ID", "ASIAIB******DFGSOBXA");
System.setProperty("AWS_SECRET_ACCESS_KEY", "r960319r4Gk52sYr0zX49zXs********asdfa1dOr5t");
System.setProperty("AWS_REGION", "us-west-2");
```

I have also set the values for access key in the application.yml : 
```
cloud:
  aws:
    region:
      static: us-west-2
    credentials:
      accessKey: ASIAIYA35T******X3JA
      secretKey: qzXAnWyafHkzm1*********S070UDkygOXne3vFQ
```
I see the following exception : 

```
org.springframework.context.ApplicationContextException: Failed to start bean 'outputBindingLifecycle'; nested exception is org.springframework.cloud.stream.binder.BinderException: Exception thrown while building outbound endpoint
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178) ~[spring-context-4.3.10.RELEASE.jar:4.3.10.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:50) ~[spring-context-4.3.10.RELEASE.jar:4.3.10.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:348) ~[spring-context-4.3.10.RELEASE.jar:4.3.10.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:151) ~[spring-context-4.3.10.RELEASE.jar:4.3.10.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:114) ~[spring-context-4.3.10.RELEASE.jar:4.3.10.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:880) ~[spring-context-4.3.10.RELEASE.jar:4.3.10.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:144) ~[spring-boot-1.5.6.RELEASE.jar:1.5.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546) ~[spring-context-4.3.10.RELEASE.jar:4.3.10.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.6.RELEASE.jar:1.5.6.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) [spring-boot-1.5.6.RELEASE.jar:1.5.6.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) [spring-boot-1.5.6.RELEASE.jar:1.5.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) [spring-boot-1.5.6.RELEASE.jar:1.5.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.6.RELEASE.jar:1.5.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.6.RELEASE.jar:1.5.6.RELEASE]
	at com.nordstrom.payment.processor.paymentprocessor.PaymentprocessorApplication.main(PaymentprocessorApplication.java:17) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_131]
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) [spring-boot-devtools-1.5.6.RELEASE.jar:1.5.6.RELEASE]
Caused by: org.springframework.cloud.stream.binder.BinderException: Exception thrown while building outbound endpoint
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindProducer(AbstractMessageChannelBinder.java:125) ~[spring-cloud-stream-1.2.2.RELEASE.jar:1.2.2.RELEASE]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindProducer(AbstractMessageChannelBinder.java:57) ~[spring-cloud-stream-1.2.2.RELEASE.jar:1.2.2.RELEASE]
	at org.springframework.cloud.stream.binder.AbstractBinder.bindProducer(AbstractBinder.java:152) ~[spring-cloud-stream-1.2.2.RELEASE.jar:1.2.2.RELEASE]
	at org.springframework.cloud.stream.binding.BindingService.bindProducer(BindingService.java:124) ~[spring-cloud-stream-1.2.2.RELEASE.jar:1.2.2.RELEASE]
	at org.springframework.cloud.stream.binding.BindableProxyFactory.bindOutputs(BindableProxyFactory.java:238) ~[spring-cloud-stream-1.2.2.RELEASE.jar:1.2.2.RELEASE]
	at org.springframework.cloud.stream.binding.OutputBindingLifecycle.start(OutputBindingLifecycle.java:57) ~[spring-cloud-stream-1.2.2.RELEASE.jar:1.2.2.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:175) ~[spring-context-4.3.10.RELEASE.jar:4.3.10.RELEASE]
	... 19 common frames omitted
Caused by: com.amazonaws.services.kinesis.model.AmazonKinesisException: The security token included in the request is invalid. (Service: AmazonKinesis; Status Code: 400; Error Code: UnrecognizedClientException; Request ID: d9300728-c99d-7909-8b20-0d6464febb63)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1587) ~[aws-java-sdk-core-1.11.177.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1257) ~[aws-java-sdk-core-1.11.177.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1029) ~[aws-java-sdk-core-1.11.177.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:741) ~[aws-java-sdk-core-1.11.177.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:715) ~[aws-java-sdk-core-1.11.177.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:697) ~[aws-java-sdk-core-1.11.177.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:665) ~[aws-java-sdk-core-1.11.177.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:647) ~[aws-java-sdk-core-1.11.177.jar:na]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:511) ~[aws-java-sdk-core-1.11.177.jar:na]
	at com.amazonaws.services.kinesis.AmazonKinesisClient.doInvoke(AmazonKinesisClient.java:2219) ~[aws-java-sdk-kinesis-1.11.177.jar:na]
	at com.amazonaws.services.kinesis.AmazonKinesisClient.invoke(AmazonKinesisClient.java:2195) ~[aws-java-sdk-kinesis-1.11.177.jar:na]
	at com.amazonaws.services.kinesis.AmazonKinesisClient.executeDescribeStream(AmazonKinesisClient.java:738) ~[aws-java-sdk-kinesis-1.11.177.jar:na]
	at com.amazonaws.services.kinesis.AmazonKinesisClient.describeStream(AmazonKinesisClient.java:714) ~[aws-java-sdk-kinesis-1.11.177.jar:na]
	at com.amazonaws.services.kinesis.AmazonKinesisClient.describeStream(AmazonKinesisClient.java:750) ~[aws-java-sdk-kinesis-1.11.177.jar:na]
	at org.springframework.cloud.stream.binder.kinesis.provisioning.KinesisStreamProvisioner.createOrUpdate(KinesisStreamProvisioner.java:90) ~[classes/:na]
	at org.springframework.cloud.stream.binder.kinesis.provisioning.KinesisStreamProvisioner.provisionProducerDestination(KinesisStreamProvisioner.java:71) ~[classes/:na]
	at org.springframework.cloud.stream.binder.kinesis.provisioning.KinesisStreamProvisioner.provisionProducerDestination(KinesisStreamProvisioner.java:45) ~[classes/:na]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindProducer(AbstractMessageChannelBinder.java:110) ~[spring-cloud-stream-1.2.2.RELEASE.jar:1.2.2.RELEASE]
	... 25 common frames omitted
```

**Comment by sabbyanandan** [comment]
Hi, @pavankumarchaitanya: Thanks for reporting. It'd be better if you scrub/mask the access credentials from the description - please update it.

**Comment by artembilan** [comment]
You know, you have just shared your AWS credentials.
And what is interesting they are different from system properties to the values in YAML.

Consider to remove them.

OTOH, it isn't clear why you think your authentication problem is related to Kinesis Binder...

**Comment by pavankumarchaitanya** [comment]
I have changed the characters in the credentials that I have provided. I'm trying to connect to Kinesis using the binder API. Also, unlike the details mentioned in https://github.com/awslabs/amazon-kinesis-scaling-utils/issues/5 , in this case, I think the code is relying on ContextCredentialsAutoConfiguration for getting the configuration. I couldn't find any other reference or similar issue when I googled for it. So I thought it'd be good to post it in the spring-cloud-stream-binder-aws-kinesis project because that's the dependency I'm using to connect to Kinesis. Kindly let me know next steps.

**Comment by artembilan** [comment]
That's correct. This project is based on the [Spring Cloud AWS](https://github.com/spring-cloud/spring-cloud-aws) (read its README, please, for more info), from where definitely the `ContextCredentialsAutoConfiguration` is used with its logic around `cloud.aws.credentials.` application properties.

The binder is based on simple configuration on the other hand:
```
@Bean
public AmazonKinesisAsync amazonKinesis(
		AWSCredentialsProvider awsCredentialsProvider,
		RegionProvider regionProvider) {

	return AmazonKinesisAsyncClientBuilder.standard()
			.withCredentials(awsCredentialsProvider)
			.withRegion(regionProvider.getRegion().getName())
			.build();
}
```

Do you see that we are missing anything here?

**Comment by pavankumarchaitanya** [comment]
I'm getting this exception in KinesisStreamProvisioner.java @ line	

DescribeStreamResult streamResult = amazonKinesis.describeStream(name);

I guess it's not an issue with this project. But just in case, mentioned below is the stack trace : 


Thread [main] (Running)	
	Thread [Thread-1] (Running)	
	Thread [restartedMain] (Suspended (exception AmazonKinesisException))	
		owns: Object  (id=55067)	
		AmazonHttpClient$RequestExecutor<Output>.executeHelper() line: 1036	
		AmazonHttpClient$RequestExecutor<Output>.doExecute() line: 741	
		AmazonHttpClient$RequestExecutor<Output>.executeWithTimer() line: 715	
		AmazonHttpClient$RequestExecutor<Output>.execute() line: 697	
		AmazonHttpClient$RequestExecutor<Output>.access$500(AmazonHttpClient$RequestExecutor) line: 665	
		AmazonHttpClient$RequestExecutionBuilderImpl.execute(HttpResponseHandler<Output>) line: 647	
		AmazonHttpClient.execute(Request<?>, HttpResponseHandler<AmazonWebServiceResponse<T>>, HttpResponseHandler<AmazonServiceException>, ExecutionContext) line: 511	
		AmazonKinesisAsyncClient(AmazonKinesisClient).doInvoke(Request<Y>, HttpResponseHandler<AmazonWebServiceResponse<X>>, ExecutionContext) line: 2219	
		AmazonKinesisAsyncClient(AmazonKinesisClient).invoke(Request<Y>, HttpResponseHandler<AmazonWebServiceResponse<X>>, ExecutionContext) line: 2195	
		AmazonKinesisAsyncClient(AmazonKinesisClient).executeDescribeStream(DescribeStreamRequest) line: 738	
		AmazonKinesisAsyncClient(AmazonKinesisClient).describeStream(DescribeStreamRequest) line: 714	
		AmazonKinesisAsyncClient(AmazonKinesisClient).describeStream(String) line: 750	
		KinesisStreamProvisioner.createOrUpdate(String, Integer) line: 90	
		KinesisStreamProvisioner.provisionProducerDestination(String, ExtendedProducerProperties<KinesisProducerProperties>) line: 71	
		KinesisStreamProvisioner.provisionProducerDestination(String, ProducerProperties) line: 45	
		KinesisMessageChannelBinder(AbstractMessageChannelBinder<C,P,PP>).doBindProducer(String, MessageChannel, P) line: 110	
		KinesisMessageChannelBinder(AbstractMessageChannelBinder<C,P,PP>).doBindProducer(String, Object, ProducerProperties) line: 57	
		KinesisMessageChannelBinder(AbstractBinder<T,C,P>).bindProducer(String, T, P) line: 152	
		BindingService.bindProducer(T, String) line: 124	
		BindableProxyFactory.bindOutputs(BindingService) line: 238	
		OutputBindingLifecycle.start() line: 57	
		DefaultLifecycleProcessor.doStart(Map<String,Lifecycle>, String, boolean) line: 175	
		DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor, Map, String, boolean) line: 50	
		DefaultLifecycleProcessor$LifecycleGroup.start() line: 348	
		DefaultLifecycleProcessor.startBeans(boolean) line: 151	
		DefaultLifecycleProcessor.onRefresh() line: 114	
		AnnotationConfigEmbeddedWebApplicationContext(AbstractApplicationContext).finishRefresh() line: 880	
		AnnotationConfigEmbeddedWebApplicationContext(EmbeddedWebApplicationContext).finishRefresh() line: 144	
		AnnotationConfigEmbeddedWebApplicationContext(AbstractApplicationContext).refresh() line: 546	
		AnnotationConfigEmbeddedWebApplicationContext(EmbeddedWebApplicationContext).refresh() line: 122	
		SpringApplication.refresh(ApplicationContext) line: 693	
		SpringApplication.refreshContext(ConfigurableApplicationContext) line: 360	
		SpringApplication.run(String...) line: 303	
		SpringApplication.run(Object[], String[]) line: 1118	
		SpringApplication.run(Object, String...) line: 1107	
		PaymentprocessorApplication.main(String[]) line: 17	
		NativeMethodAccessorImpl.invoke0(Method, Object, Object[]) line: not available [native method]	
		NativeMethodAccessorImpl.invoke(Object, Object[]) line: 62	
		DelegatingMethodAccessorImpl.invoke(Object, Object[]) line: 43	
		Method.invoke(Object, Object...) line: 498	
		RestartLauncher.run() line: 49

**Comment by pavankumarchaitanya** [comment]
I am able to publish to Kinesis using the API, had to pass aws_security_token. The AWSCredentialsProviderChain picked up credentials from ~/.aws/credentials file. Thank you very much for the prompt response and support.

**Comment by artembilan** [comment]
@pavankumarchaitanya ,

Glad to hear!

Please, consider in the future to properly format your posts. Right now it isn't readable in the part of stack trace: https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by pavankumarchaitanya** [comment]
Sure Artembilan, thank you.
