### ISSUE TITLE
Kinesis binder locks timed out and messages not delivered

### ISSUE THREAD

**Issue by RomanAbakumov** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#190]

**Comment by artembilan** [comment]
Duplicate of https://github.com/spring-cloud/spring-cloud-stream-binder-aws-kinesis/issues/186.

Please, consider to upgrade to the latest Kinesis Binder: https://spring.io/blog/2023/03/27/spring-integration-for-aws-3-0-0-m2-and-spring-cloud-stream-kinesis-binder-4.

For the current version I'd suggest to use a short `leaseDuration`.

**Comment by RomanAbakumov** [comment]
Thanks for the quick reply.
I've tried to reduce the leaseDuration, but it didn't help.
I will try with the new milestone version libs, do you have an estimation of when it will be released?

**Comment by artembilan** [comment]
In May. Or better to say when Spring Cloud AWS 3.0 is GA.

**Comment by RomanAbakumov** [comment]
@artembilan 
I've tried to use mentioned versions, but while it sends and receive a messages I getting exceptions, and it was not happening with the old versions.
Maybe I need to configure the endpoint for local stack in the different place, but the message is misleading in this case.

*To Reproduce*
Steps to reproduce the behavior:

1. Clone the repository https://github.com/RomanAbakumov/kinesis-lock-issues-demo
2. run localstack using startLocalstack.cmd/startLocalstack.sh
3. start application using mvnw spring-boot:run

Exception
`2023-05-01T12:20:10.378-04:00 ERROR 25124 --- [-response-1-316] o.s.i.a.outbound.KinesisMessageHandler   : Failed to send async reply: GenericMessage [payload=byte[11], headers={errorChannel=org.springframework.integration.channel.PublishSubscribeChannel@4b7587bb, aws_shard=shardId-000000000015, aws_sequenceNumber=49640352981821805482850094172893096755799942984020001010, aws_serviceResult=PutRecordResponse(ShardId=shardId-000000000015, SequenceNumber=49640352981821805482850094172893096755799942984020001010, EncryptionType=NONE), id=469a6c17-5f59-2b0b-2e04-eaa39c0e9594, contentType=application/json, target-protocol=kafka, timestamp=1682958010378}]

org.springframework.messaging.core.DestinationResolutionException: no output-channel or replyChannel header available
	at org.springframework.integration.handler.AbstractMessageProducingHandler.sendOutput(AbstractMessageProducingHandler.java:479) ~[spring-integration-core-6.0.3.jar:6.0.3]
	at org.springframework.integration.handler.AbstractMessageProducingHandler$ReplyFutureCallback.accept(AbstractMessageProducingHandler.java:581) ~[spring-integration-core-6.0.3.jar:6.0.3]
	at org.springframework.integration.handler.AbstractMessageProducingHandler$ReplyFutureCallback.accept(AbstractMessageProducingHandler.java:563) ~[spring-integration-core-6.0.3.jar:6.0.3]
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) ~[na:na]
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncApiCallMetricCollectionStage.lambda$execute$0(AsyncApiCallMetricCollectionStage.java:56) ~[sdk-core-2.20.30.jar:na]
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) ~[na:na]
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncApiCallTimeoutTrackingStage.lambda$execute$2(AsyncApiCallTimeoutTrackingStage.java:69) ~[sdk-core-2.20.30.jar:na]
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) ~[na:na]
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.lambda$attemptExecute$1(AsyncRetryableStage.java:177) ~[sdk-core-2.20.30.jar:na]
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) ~[na:na]
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.lambda$null$0(MakeAsyncHttpRequestStage.java:105) ~[sdk-core-2.20.30.jar:na]
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) ~[na:na]
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.lambda$executeHttpRequest$3(MakeAsyncHttpRequestStage.java:163) ~[sdk-core-2.20.30.jar:na]
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-05-01T12:20:10.379-04:00 ERROR 25124 --- [-response-1-316] o.s.integration.handler.LoggingHandler   : org.springframework.messaging.core.DestinationResolutionException: no output-channel or replyChannel header available
	at org.springframework.integration.handler.AbstractMessageProducingHandler.sendOutput(AbstractMessageProducingHandler.java:479)
	at org.springframework.integration.handler.AbstractMessageProducingHandler$ReplyFutureCallback.accept(AbstractMessageProducingHandler.java:581)
	at org.springframework.integration.handler.AbstractMessageProducingHandler$ReplyFutureCallback.accept(AbstractMessageProducingHandler.java:563)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncApiCallMetricCollectionStage.lambda$execute$0(AsyncApiCallMetricCollectionStage.java:56)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncApiCallTimeoutTrackingStage.lambda$execute$2(AsyncApiCallTimeoutTrackingStage.java:69)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.lambda$attemptExecute$1(AsyncRetryableStage.java:177)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.lambda$null$0(MakeAsyncHttpRequestStage.java:105)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.lambda$executeHttpRequest$3(MakeAsyncHttpRequestStage.java:163)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
`

**Comment by RomanAbakumov** [comment]
Is it configured incorrectly?

**Comment by RomanAbakumov** [comment]
Yeah, I confirm, this error doesn't appear with snapshot, thanks

**Comment by RomanAbakumov** [comment]
While it works as it should, with no errors, and shard consumers able to allocate unused nodes I faced another issue that may need attention.
My laptop runs localstack and 3 app instances, I put it to sleep and when I wake it up I see that one app instance reports errors, and it can't recover of it for more than 30 minutes.

2023-05-01T14:54:10.459-04:00  INFO 16112 --- [esis-consumer-1] a.i.k.KinesisMessageDrivenChannelAdapter : Got an exception java.util.concurrent.CompletionException: software.amazon.awssdk.services.kinesis.model.ExpiredIteratorException: The shard iterator has expired. Shard iterators are only valid for 300 seconds (Service: Kinesis, Status Code: 400, Request ID: AKSSPO8S0D2O3C4WWIF4QKMEL8VJSL2NANQN52N899PIFJFO7I09) during [ShardConsumer{shardOffset=KinesisShardOffset{iteratorType=AFTER_SEQUENCE_NUMBER, sequenceNumber='49640352981598798030864787941543021567332992185863766098', timestamp=null, stream='stream-v0', shard='shardId-000000000005', reset=false}, state=CONSUME}] task invocation.
Process will be retried on the next iteration.

**Comment by artembilan** [comment]
Got it!
Please, raise a new GH issue in the https://github.com/spring-projects/spring-integration-aws project with more info.

It looks like we we don't catch this kind of errors in the `KinesisMessageDrivenChannelAdapter`.

**Comment by RomanAbakumov** [comment]
it looks like the locks were holding, but the iterator has expired as after restarting I saw that old messages started to be consumed.

**Comment by RomanAbakumovMH** [comment]
@artembilan 
Kinesis binder v3 has dependency to io.awspring.cloud:spring-cloud-starter-aws and  io.awspring.cloud:spring-cloud-aws-autoconfigure that allow to specify AWS configuration in application.yaml such as:
cloud:
  aws:
    region:
      static: us-east-1

Binder v4 doesn't have those dependencies so this configuration is not working.
How I can get it working with v4 binder, should I manually add dependencies?

**Comment by artembilan** [comment]
> has dependency to io.awspring.cloud:spring-cloud-starter-aws and io.awspring.cloud:spring-cloud-aws-autoconfigure

That's not correct. You can find its POM here: https://central.sonatype.com/artifact/org.springframework.cloud/spring-cloud-stream-binder-kinesis/3.0.0

As you see there is `spring-cloud-starter-aws`, but no `spring-cloud-aws-autoconfigure`.

So, what we did in v4 is just changed that dep to `spring-cloud-aws-starter`.
And looks like that `spring-cloud-aws-autoconfigure` is still there: https://github.com/awspring/spring-cloud-aws/blob/main/spring-cloud-aws-starters/spring-cloud-aws-starter/pom.xml#L17-L20.

Probably those props are changed.
In my tests I use:
```
spring.cloud.aws.region.static
```

See this Microservices Pattern implementation where I really use that Kinesis Binder v4:  https://github.com/artembilan/microservices-patterns-spring-integration/tree/main/distributed-tracing

**Comment by artembilan** [comment]
@RomanAbakumov ,

Please, raise a new issue with more details.
I'd like to see some code to determine what is wrong.

Are you really sure that you produce a message with header?
The mapping is just a part of the puzzle: if you don't produce that header, there is just nothing to map onto Kinesis record.

**Comment by RomanAbakumovMH** [comment]
Yes, we use single event stream for different kind of messages and routing based by headers.
I'll try to reproduce it in demo app.

**Comment by RomanAbakumovMH** [comment]
New bug reported https://github.com/spring-cloud/spring-cloud-stream-binder-aws-kinesis/issues/192
