### ISSUE TITLE
Issue consuming messages

### ISSUE THREAD

**Issue by oatesp** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#20]
Hi,

I'm having trouble getting a test application to consume messages from a Kinesis stream. 

I'm adding a message to the stream via the aws cli 

```
aws kinesis put-record --stream-name test-requisition --partition-key 123 --data '{"eventType":"REMINDER","requisition":null,"originator":null,"eventId":"97213bfd-74d2-4fa6-9d9e-4085c73cc985"}'
```

The application picks the message up but then throws an error

```
2017-08-30 11:16:03 DEBUG o.s.c.s.b.AbstractMessageChannelBinder$ReceivingHandler - org.springframework.cloud.stream.binder.AbstractMessageChannelBinder$ReceivingHandler@3d211e6f received message: GenericMessage [payload=byte[110], headers={aws_partitionKey=123, id=52971e06-52db-98c2-a4ba-273aed57513b, aws_shard=shardId-000000000000, aws_stream=test-requisition, aws_sequenceNumber=49576386617945185524571281180093049961781863423556976642, timestamp=1504088163316}]
2017-08-30 11:16:03 ERROR o.s.c.s.b.k.KinesisMessageChannelBinder - Could not convert message: 7B226576656E7454797065223A2252454D494E444552222C227265717569736974696F6E223A6E756C6C2C226F726967696E61746F72223A6E756C6C2C226576656E744964223A2239373231336266642D373464322D346661362D396439652D343038356337336363393835227D
java.lang.StringIndexOutOfBoundsException: String index out of range: 163
        at java.lang.String.checkBounds(String.java:385)
        at java.lang.String.<init>(String.java:425)
        at org.springframework.cloud.stream.binder.EmbeddedHeaderUtils.oldExtractHeaders(EmbeddedHeaderUtils.java:157)
        at org.springframework.cloud.stream.binder.EmbeddedHeaderUtils.extractHeaders(EmbeddedHeaderUtils.java:115)
        at org.springframework.cloud.stream.binder.EmbeddedHeaderUtils.extractHeaders(EmbeddedHeaderUtils.java:107)
        at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder$ReceivingHandler.handleRequestMessage(AbstractMessageChannelBinder.java:304)
        at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:109)
        at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:127)
        at org.springframework.integration.channel.FixedSubscriberChannel.send(FixedSubscriberChannel.java:70)
        at org.springframework.integration.channel.FixedSubscriberChannel.send(FixedSubscriberChannel.java:64)
        at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:115)
        at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:45)
        at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:105)
        at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:171)
        at org.springframework.integration.aws.inbound.kinesis.KinesisMessageDrivenChannelAdapter.access$5100(KinesisMessageDrivenChannelAdapter.java:82)
        at org.springframework.integration.aws.inbound.kinesis.KinesisMessageDrivenChannelAdapter$ShardConsumer.processRecords(KinesisMessageDrivenChannelAdapter.java:906)
        at org.springframework.integration.aws.inbound.kinesis.KinesisMessageDrivenChannelAdapter$ShardConsumer.access$3600(KinesisMessageDrivenChannelAdapter.java:688)
        at org.springframework.integration.aws.inbound.kinesis.KinesisMessageDrivenChannelAdapter$ShardConsumer$2.run(KinesisMessageDrivenChannelAdapter.java:822)
        at org.springframework.integration.aws.inbound.kinesis.KinesisMessageDrivenChannelAdapter$ConsumerInvoker.run(KinesisMessageDrivenChannelAdapter.java:1000)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
2017-08-30 11:16:03 DEBUG o.s.i.channel.DirectChannel - preSend on channel 'requisitionsIn', message: GenericMessage [payload=byte[110], headers={aws_partitionKey=123, id=b4c3c49e-2d59-ef1b-8577-3e350159c491, aws_shard=shardId-000000000000, aws_stream=test-requisition, aws_sequenceNumber=49576386617945185524571281180093049961781863423556976642, timestamp=1504088163338}]
Exception in thread "-kinesis-consumer-1" org.springframework.messaging.converter.MessageConversionException: Could not read JSON: Can not deserialize instance of java.lang.String out of START_OBJECT token
 at [Source: [B@1f86c828; line: 1, column: 1]; nested exception is com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.lang.String out of START_OBJECT token
 at [Source: [B@1f86c828; line: 1, column: 1], failedMessage=GenericMessage [payload=byte[110], headers={aws_partitionKey=123, id=b4c3c49e-2d59-ef1b-8577-3e350159c491, aws_shard=shardId-000000000000, aws_stream=test-requisition, aws_sequenceNumber=49576386617945185524571281180093049961781863423556976642, timestamp=1504088163338}]
        at org.springframework.messaging.converter.MappingJackson2MessageConverter.convertFromInternal(MappingJackson2MessageConverter.java:224)
        at org.springframework.messaging.converter.AbstractMessageConverter.fromMessage(AbstractMessageConverter.java:175)
        at org.springframework.messaging.converter.AbstractMessageConverter.fromMessage(AbstractMessageConverter.java:167)
        at org.springframework.messaging.converter.CompositeMessageConverter.fromMessage(CompositeMessageConverter.java:55)
        at org.springframework.cloud.stream.binding.MessageConverterConfigurer$ContentTypeConvertingInterceptor.preSend(MessageConverterConfigurer.java:248)
        at org.springframework.integration.channel.AbstractMessageChannel$ChannelInterceptorList.preSend(AbstractMessageChannel.java:538)
        at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:415)
        at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:373)
        at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:115)
        at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:45)
        at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:105)
        at org.springframework.integration.handler.AbstractMessageProducingHandler.sendOutput(AbstractMessageProducingHandler.java:292)
        at org.springframework.integration.handler.AbstractMessageProducingHandler.produceOutput(AbstractMessageProducingHandler.java:212)
        at org.springframework.integration.handler.AbstractMessageProducingHandler.sendOutputs(AbstractMessageProducingHandler.java:129)
        at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:115)
        at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:127)
        at org.springframework.integration.channel.FixedSubscriberChannel.send(FixedSubscriberChannel.java:70)
        at org.springframework.integration.channel.FixedSubscriberChannel.send(FixedSubscriberChannel.java:64)
        at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:115)
        at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:45)
        at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:105)
        at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:171)
        at org.springframework.integration.aws.inbound.kinesis.KinesisMessageDrivenChannelAdapter.access$5100(KinesisMessageDrivenChannelAdapter.java:82)
        at org.springframework.integration.aws.inbound.kinesis.KinesisMessageDrivenChannelAdapter$ShardConsumer.processRecords(KinesisMessageDrivenChannelAdapter.java:906)
        at org.springframework.integration.aws.inbound.kinesis.KinesisMessageDrivenChannelAdapter$ShardConsumer.access$3600(KinesisMessageDrivenChannelAdapter.java:688)
        at org.springframework.integration.aws.inbound.kinesis.KinesisMessageDrivenChannelAdapter$ShardConsumer$2.run(KinesisMessageDrivenChannelAdapter.java:822)
        at org.springframework.integration.aws.inbound.kinesis.KinesisMessageDrivenChannelAdapter$ConsumerInvoker.run(KinesisMessageDrivenChannelAdapter.java:1000)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.lang.String out of START_OBJECT token
 at [Source: [B@1f86c828; line: 1, column: 1]
        at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:270)
        at com.fasterxml.jackson.databind.DeserializationContext.reportMappingException(DeserializationContext.java:1234)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1122)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1075)
        at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:60)
        at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:11)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3798)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2959)
        at org.springframework.messaging.converter.MappingJackson2MessageConverter.convertFromInternal(MappingJackson2MessageConverter.java:211)
        ... 29 more
```

Has anyone else encountered this issue while testing? Is something missing from the message I am adding to the stream that spring cloud stream is expecting? 

I have read that the message may require headers but I can see headers in the received message.
```
received message: GenericMessage [payload=byte[110], headers={aws_partitionKey=123, id=52971e06-52db-98c2-a4ba-273aed57513b, aws_shard=shardId-000000000000, aws_stream=test-requisition, aws_sequenceNumber=49576386617945185524571281180093049961781863423556976642, timestamp=1504088163316}]
```

Any suggestion of where else I can look to resolve this would be appreciated.

Thanks, 
Peter.

**Comment by artembilan** [comment]
Consider to use `spring.cloud.stream.default.consumer.headerMode=raw`: https://docs.spring.io/spring-cloud-stream/docs/Chelsea.SR2/reference/htmlsingle/index.html#_consumer_properties

>   When set to `raw`, disables header parsing on input. Effective only for messaging middleware that does not support message headers natively and requires header embedding. Useful when inbound data is coming from outside Spring Cloud Stream applications.

>    Default: `embeddedHeaders`.

The piece of code who is guilty in what you see looks like:
```
if (this.extractEmbeddedHeaders) {
				try {
					messageValues = EmbeddedHeaderUtils.extractHeaders((Message<byte[]>) requestMessage,
							true);
				}
				catch (Exception e) {
					AbstractMessageChannelBinder.this.logger.error(
							EmbeddedHeaderUtils.decodeExceptionMessage(
									requestMessage),
							e);
					messageValues = new MessageValues(requestMessage);
				}
				messageValues = deserializePayloadIfNecessary(messageValues);
			}
```
Pay attention to that `catch` and `logger.error()`.

**Comment by oatesp** [comment]
Thanks for this.

I have added the property and the stack trace changes but I still have an error. The stack trace is now 

`2017-08-30 12:18:05 DEBUG o.s.c.s.b.AbstractMessageChannelBinder$ReceivingHandler - org.springframework.cloud.stream.binder.AbstractMessageChannelBinder$ReceivingHandler@3c9efc2f received message: GenericMessage [payload=byte[110], headers={aws_partitionKey=123, id=831b6412-3d0e-7e91-40e9-bd8022a775bf, aws_shard=shardId-000000000000, aws_stream=test-requisition, aws_sequenceNumber=49576386617945185524571282073243818715611309857726005250, timestamp=1504091885803}]
2017-08-30 12:18:05 DEBUG o.s.i.channel.DirectChannel - preSend on channel 'requisitionsIn', message: GenericMessage [payload=byte[110], headers={aws_partitionKey=123, id=6e9b22e4-480b-9dc5-1b79-9dff86b1e67d, aws_shard=shardId-000000000000, aws_stream=test-requisition, aws_sequenceNumber=49576386617945185524571282073243818715611309857726005250, timestamp=1504091885804}]
Exception in thread "-kinesis-consumer-1" org.springframework.messaging.converter.MessageConversionException: Could not read JSON: Can not deserialize instance of java.lang.String out of START_OBJECT token
 at [Source: [B@5cbeb590; line: 1, column: 1]; nested exception is com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.lang.String out of START_OBJECT token
 at [Source: [B@5cbeb590; line: 1, column: 1], failedMessage=GenericMessage [payload=byte[110], headers={aws_partitionKey=123, id=6e9b22e4-480b-9dc5-1b79-9dff86b1e67d, aws_shard=shardId-000000000000, aws_stream=test-requisition, aws_sequenceNumber=49576386617945185524571282073243818715611309857726005250, timestamp=1504091885804}]
        at org.springframework.messaging.converter.MappingJackson2MessageConverter.convertFromInternal(MappingJackson2MessageConverter.java:224)
        at org.springframework.messaging.converter.AbstractMessageConverter.fromMessage(AbstractMessageConverter.java:175)
        at org.springframework.messaging.converter.AbstractMessageConverter.fromMessage(AbstractMessageConverter.java:167)
        at org.springframework.messaging.converter.CompositeMessageConverter.fromMessage(CompositeMessageConverter.java:55)
        at org.springframework.cloud.stream.binding.MessageConverterConfigurer$ContentTypeConvertingInterceptor.preSend(MessageConverterConfigurer.java:248)
        at org.springframework.integration.channel.AbstractMessageChannel$ChannelInterceptorList.preSend(AbstractMessageChannel.java:538)
        at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:415)
        at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:373)
        at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:115)
        at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:45)
        at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:105)
        at org.springframework.integration.handler.AbstractMessageProducingHandler.sendOutput(AbstractMessageProducingHandler.java:292)
        at org.springframework.integration.handler.AbstractMessageProducingHandler.produceOutput(AbstractMessageProducingHandler.java:212)
        at org.springframework.integration.handler.AbstractMessageProducingHandler.sendOutputs(AbstractMessageProducingHandler.java:129)
        at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:115)
        at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:127)
        at org.springframework.integration.channel.FixedSubscriberChannel.send(FixedSubscriberChannel.java:70)
        at org.springframework.integration.channel.FixedSubscriberChannel.send(FixedSubscriberChannel.java:64)
        at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:115)
        at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:45)
        at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:105)
        at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:171)
        at org.springframework.integration.aws.inbound.kinesis.KinesisMessageDrivenChannelAdapter.access$5100(KinesisMessageDrivenChannelAdapter.java:82)
        at org.springframework.integration.aws.inbound.kinesis.KinesisMessageDrivenChannelAdapter$ShardConsumer.processRecords(KinesisMessageDrivenChannelAdapter.java:906)
        at org.springframework.integration.aws.inbound.kinesis.KinesisMessageDrivenChannelAdapter$ShardConsumer.access$3600(KinesisMessageDrivenChannelAdapter.java:688)
        at org.springframework.integration.aws.inbound.kinesis.KinesisMessageDrivenChannelAdapter$ShardConsumer$2.run(KinesisMessageDrivenChannelAdapter.java:822)
        at org.springframework.integration.aws.inbound.kinesis.KinesisMessageDrivenChannelAdapter$ConsumerInvoker.run(KinesisMessageDrivenChannelAdapter.java:1000)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.lang.String out of START_OBJECT token
 at [Source: [B@5cbeb590; line: 1, column: 1]
        at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:270)
        at com.fasterxml.jackson.databind.DeserializationContext.reportMappingException(DeserializationContext.java:1234)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1122)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1075)
        at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:60)
        at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:11)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3798)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2959)
        at org.springframework.messaging.converter.MappingJackson2MessageConverter.convertFromInternal(MappingJackson2MessageConverter.java:211)
        ... 29 more`


I do recall seeing this error `Can not deserialize instance of java.lang.String out of START_OBJECT token` in my original test project for the kinesis binder and think I had a ticket raised for that. However that error went away in the test project, possible due to a change in the binder code. 

I can't understand why this error is occurring in this new test project.

**Comment by artembilan** [comment]
@oatesp ,

How about to clean up the stream of the old data and start again with the fresh data?

**Comment by artembilan** [comment]
@oatesp ,

what is your `@StreamListener`?
How about to expect `Map<>` there instead of `String` ?

**Comment by artembilan** [comment]
@oatesp ,

you know would be great to have your use-case as a test in the project.
Consider to PR something on the matter to play with similar problems in the future.
Thanks

**Comment by oatesp** [comment]
Hi,

I've tried deleting the streams and starting again, that didn't have an affect.

My streamListener looks like 
`@Component
@Slf4j
@EnableBinding(Channels.class)
class RequisitionsListener {

    @Inject
    private ApplicationEventPublisher publisher;

    @StreamListener(Channels.REQUISITIONS_IN)
    void processPurchaseRequisitionEvent(final PurchaseRequisitionEvent event) throws IOException {
        log.info("Received event {}", event);
        this.publisher.publishEvent(event);
    }
}`

I'm not sure I understand what you mean by expecting Map instead of String, where would I define that?

I can certainly PR my use case test application, I'll try to do this on Monday.

Thanks,

**Comment by garyrussell** [comment]
>I'm not sure I understand what you mean by expecting Map instead of String, where would I define that?

We were speculating that your `StreamListener` took a `String` argument because, for some reason, Jackson is trying to decode your JSON as a String (which must start with `"`).

>Can not deserialize instance of java.lang.String out of START_OBJECT token

It's not clear why Jackson would do this, given you have a concrete type for your parameter.

**Comment by artembilan** [comment]
So, would be great to get a simple test-case in the project code against Kinesalite to debug and be protected from the future breaking changes.

**Comment by oatesp** [comment]
I've done some further investigation and found that the way I add the messages to the stream affects the success of the message being read by the application. 

When using a standard kinesis put-record request I get the START_TOKEN error.

When I use a spring cloud applicaiton to place the message using the GenericMessage there is no error.

If I read the stream directly I can see that the spring placed message is adding a new character and information about content type to the message data. I'm not sure what this character is.

		`�
		 contentType"application/json"{"id":null,"subject":{"id":"a2d4e821-76c7-4748-9b9c-922896c019d9","name":"pen"},"type":"ORDER","originator":"Sword"}`



Further complication occurs if I try to read a put-record message due to the header type. To get a read I need to use.       
`default:
        consumer: 
          headerMode: raw`
		  
However when I use this any message placed by a spring cloud applicaiton fails to be read with an unrecognised character error. I can see the raw message looks like 

`�
                             contentType"application/json"{"id":null,"subject":{"id":"8fcfa18e-38e3-4b13-b0a7-5828e9c70961","name":"pen"},"type":"ORDER","originator":"Sword"}`
							 
Notice the strange character and the space between it and the message. 


Does anyone have any idea what this character is that is being added? It's preventing testing via put-record requests to kinesis. 

Is there also some way to consume both records set by another spring cloud application and records placed directly on a stream by a put-record request?


I'm working on making my experiments into a test case that I can PR up, hopefully have something today.

**Comment by artembilan** [comment]
Great investigation, @oatesp !

I think if you use `raw` mode for reading data, you should use the same for sending data.
As you do that via `aws kinesis put-record`, of course.

All you see, IMO, is a result of `embeddedHeaders` function.

**Comment by artembilan** [comment]
Any news on the matter?

Maybe we can close it as obsolete?

Thanks

**Comment by oatesp** [comment]
This isn't causing an issue in a more realistic test application so I think you can close it as obsolete.

I believe the way I was testing the stream was the cause of the problem.

Thanks,
