### ISSUE TITLE
An update to spring-cloud-stream 1.30.BUILD-SNAPSHOT has broken this binder

### ISSUE THREAD

**Issue by oatesp** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#22]
Commit 0eab8a5fa700e19c2a026722418d920955d38c7a in spring-cloud-stream altered the signature of the method `protected abstract MessageHandler createProducerMessageHandler(ProducerDestination destination,
			P producerProperties, MessageChannel errorChannel)
			throws Exception;`

This exposed in my test application that I had been previously running the kinesis binder with an older spring-cloud-stream. Having forced the test application to use the SNAPSHOT I now see an error `java.lang.NoSuchMethodError: org.springframework.cloud.stream.binding.StreamListenerMessageHandler.setNotPropagatedHeaders([Ljava/lang/String;)V
	at org.springframework.cloud.stream.binding.StreamListenerMessageHandler.<init>(StreamListenerMessageHandler.java:40)`

Thought I'd raise this here, it's blocking a PR in spring-cloud-stream-samples and the raising of the PR to tackle [https://github.com/spring-cloud/spring-cloud-stream-binder-aws-kinesis/issues/18](url)

I'm not sure how to determine the breaking change or what I can do to resolve the dependency issue. I could set spring-cloud-stream in this binder to be version 1.2.2.RELEASE which appears to work.

**Comment by artembilan** [comment]
@oatesp ,

Have just pushed the fix into the `master`. 
Just `pull upstream master` and rebase your local branch to go ahead with your important work!

**Comment by oatesp** [comment]
I'm still getting a startup failure in my test app.

`2017-09-07 16:11:24 DEBUG o.s.b.l.ClasspathLoggingApplicationListener - Application failed to start with classpath: [file:/Users/Peter.Oates/code/src/git/cloud/spring/spring-forks/spring-cloud-stream-samples/kinesis-produce-consume/target/classes/, file:/Users/Peter.Oates/code/src/git/cloud/spring/spring-forks/spring-cloud-stream-binder-aws-kinesis/spring-cloud-stream-binder-kinesis/target/classes/, file:/Users/Peter.Oates/code/src/git/cloud/spring/spring-forks/spring-cloud-stream-binder-aws-kinesis/spring-cloud-stream-binder-kinesis-core/target/classes/]
2017-09-07 16:11:24 ERROR o.s.boot.SpringApplication - Application startup failed
java.lang.NoSuchMethodError: org.springframework.cloud.stream.binding.StreamListenerMessageHandler.setNotPropagatedHeaders([Ljava/lang/String;)V
	at org.springframework.cloud.stream.binding.StreamListenerMessageHandler.<init>(StreamListenerMessageHandler.java:40)
	at org.springframework.cloud.stream.binding.StreamListenerAnnotationBeanPostProcessor.afterSingletonsInstantiated(StreamListenerAnnotationBeanPostProcessor.java:358)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:781)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:370)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1162)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1151)
	at kinesis.KinesisApplication.main(KinesisApplication.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)`

Version 1.2.2.RELEASE does work.

**Comment by artembilan** [comment]
The `setNotPropagatedHeaders()` is there since Spring Integration `4.3.10`. Need to see your dependencies to determine why the proper version isn't pulled automatically.
