### ISSUE TITLE
com.fasterxml.jackson.core.JsonParseException at rest

### ISSUE THREAD

**Issue by komushi** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#45]
With Kinesis M1 binder when a source/sink/processor app is at rest the following exception will come up occasionally.

```
2018-03-15 08:20:23.569 INFO 1 --- [esis-consumer-1] com.amazonaws.protocol.json.JsonContent : Unable to parse HTTP response content
com.fasterxml.jackson.core.JsonParseException: Illegal length for VALUE_STRING: 2477946696968059424
at [Source: (byte[])"
{
    "code": "ServiceUnavailable",
    "message": "The request has failed due to a temporary failure of the server."
}
"; line: -1, column: 9]
at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1798) ~[jackson-core-2.9.3.jar!/:2.9.3]
at com.fasterxml.jackson.dataformat.cbor.CBORParser._decodeExplicitLength(CBORParser.java:2757) ~[jackson-dataformat-cbor-2.9.3.jar!/:2.9.3]
at com.fasterxml.jackson.dataformat.cbor.CBORParser._finishTextToken(CBORParser.java:1931) ~[jackson-dataformat-cbor-2.9.3.jar!/:2.9.3]
at com.fasterxml.jackson.dataformat.cbor.CBORParser.getText(CBORParser.java:1318) ~[jackson-dataformat-cbor-2.9.3.jar!/:2.9.3]
at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeAny(JsonNodeDeserializer.java:523) ~[jackson-databind-2.9.3.jar!/:2.9.3]
at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:73) ~[jackson-databind-2.9.3.jar!/:2.9.3]
at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:15) ~[jackson-databind-2.9.3.jar!/:2.9.3]
at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4044) ~[jackson-databind-2.9.3.jar!/:2.9.3]
at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2559) ~[jackson-databind-2.9.3.jar!/:2.9.3]
at com.amazonaws.protocol.json.JsonContent.parseJsonContent(JsonContent.java:72) [aws-java-sdk-core-1.11.251.jar!/:na]
at com.amazonaws.protocol.json.JsonContent.<init>(JsonContent.java:64) [aws-java-sdk-core-1.11.251.jar!/:na]
at com.amazonaws.protocol.json.JsonContent.createJsonContent(JsonContent.java:54) [aws-java-sdk-core-1.11.251.jar!/:na]
at com.amazonaws.http.JsonErrorResponseHandler.handle(JsonErrorResponseHandler.java:61) [aws-java-sdk-core-1.11.251.jar!/:na]
at com.amazonaws.http.JsonErrorResponseHandler.handle(JsonErrorResponseHandler.java:33) [aws-java-sdk-core-1.11.251.jar!/:na]
at com.amazonaws.http.AwsErrorResponseHandler.handleAse(AwsErrorResponseHandler.java:50) [aws-java-sdk-core-1.11.251.jar!/:na]
at com.amazonaws.http.AwsErrorResponseHandler.handle(AwsErrorResponseHandler.java:38) [aws-java-sdk-core-1.11.251.jar!/:na]
at com.amazonaws.http.AwsErrorResponseHandler.handle(AwsErrorResponseHandler.java:24) [aws-java-sdk-core-1.11.251.jar!/:na]
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1621) [aws-java-sdk-core-1.11.251.jar!/:na]
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1304) [aws-java-sdk-core-1.11.251.jar!/:na]
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1056) [aws-java-sdk-core-1.11.251.jar!/:na]
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743) [aws-java-sdk-core-1.11.251.jar!/:na]
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717) [aws-java-sdk-core-1.11.251.jar!/:na]
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699) [aws-java-sdk-core-1.11.251.jar!/:na]
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667) [aws-java-sdk-core-1.11.251.jar!/:na]
at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649) [aws-java-sdk-core-1.11.251.jar!/:na]
at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513) [aws-java-sdk-core-1.11.251.jar!/:na]
at com.amazonaws.services.kinesis.AmazonKinesisClient.doInvoke(AmazonKinesisClient.java:2276) [aws-java-sdk-kinesis-1.11.251.jar!/:na]
at com.amazonaws.services.kinesis.AmazonKinesisClient.invoke(AmazonKinesisClient.java:2252) [aws-java-sdk-kinesis-1.11.251.jar!/:na]
at com.amazonaws.services.kinesis.AmazonKinesisClient.executeGetRecords(AmazonKinesisClient.java:1062) [aws-java-sdk-kinesis-1.11.251.jar!/:na]
at com.amazonaws.services.kinesis.AmazonKinesisClient.getRecords(AmazonKinesisClient.java:1038) [aws-java-sdk-kinesis-1.11.251.jar!/:na]
at org.springframework.integration.aws.inbound.kinesis.KinesisMessageDrivenChannelAdapter$ShardConsumer.getRecords(KinesisMessageDrivenChannelAdapter.java:869) [spring-integration-aws-2.0.0.M1.jar!/:na]
at org.springframework.integration.aws.inbound.kinesis.KinesisMessageDrivenChannelAdapter$ShardConsumer.lambda$processTask$1(KinesisMessageDrivenChannelAdapter.java:828) [spring-integration-aws-2.0.0.M1.jar!/:na]
at org.springframework.integration.aws.inbound.kinesis.KinesisMessageDrivenChannelAdapter$ConsumerInvoker.run(KinesisMessageDrivenChannelAdapter.java:1018) ~[spring-integration-aws-2.0.0.M1.jar!/:na]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_152]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_152]
at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_152]
```

**Comment by artembilan** [comment]
@komushi ,

I'm so sorry, but this is unclear.

What is that `rest`?

Looking to the stack trace provided, seems for me the typical error from the AWS. How is it related to our Kinesis Binder?

Thanks

**Comment by komushi** [comment]
Rest means when there is no events happening, no inputs. I am using the default scs apps. Such as log-sink, s3-sink, filter-processor.

**Comment by artembilan** [comment]
OK, thanks. Although that doesn't help. Too complicated for such a simple clear exception.
Anyway I think there is nothing to do from our side: that is core AWS exception. 
Fully not sure what you would like to get from us.

Maybe would be better to ask such a question on the AWS forums?

**Comment by komushi** [comment]
This happens at 'org.springframework.integration.aws.inbound.kinesis.KinesisMessageDrivenChannelAdapter$ShardConsumer.getRecords'.

When there is no inbound messages but still the ShardConsumer.getRecords will be used. Is this an expected behavior?

Thanks

**Comment by artembilan** [comment]
Right, that' how things work.
We can't know if there is something in the stream if we don't poll data from there. And that we can do exactly with the `GetRecordsRequest` to Kinesis. And we do the periodically with some `idleBetweenPolls` interval.

One more time: please, consult with AWS support to determine the reason of that `ServiceUnavailable`.
There is nothing from Spring perspective.

*Closed as non-related*
