### ISSUE TITLE
partitionKeyExpression is evaluated after message conversion

### ISSUE THREAD

**Issue by dittos** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#60]
Spring Cloud Stream allows `partitionKeyExpression` to access the original `payload` (before being converted to `byte[]`). [Related docs](https://docs.spring.io/spring-cloud-stream/docs/Fishtown.M1/reference/htmlsingle/#spring-cloud-stream-overview-configuring-output-bindings-partitioning)

However when using Kinesis Binder, `payload` in `partitionKeyExpression` is `byte[]` type, causing the following exception (`partitionKeyExpression` was set to `payload.vehicleId`):

```
org.springframework.messaging.MessageHandlingException: error occurred in message handler [org.springframework.integration.aws.outbound.KinesisMessageHandler@a1fd1f6]; nested exception is org.springframework.expression.spel.SpelEvaluationException: EL1008E: Property or field 'vehicleId' cannot be found on object of type 'byte[]' - maybe not public or not valid?
	at org.springframework.integration.support.utils.IntegrationUtils.wrapInHandlingExceptionIfNecessary(IntegrationUtils.java:184) ~[spring-integration-core-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:175) ~[spring-integration-core-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder$SendingHandler.handleMessageInternal(AbstractMessageChannelBinder.java:725) ~[spring-cloud-stream-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:165) ~[spring-integration-core-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:116) ~[spring-integration-core-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:132) ~[spring-integration-core-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:105) ~[spring-integration-core-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:73) ~[spring-integration-core-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:445) ~[spring-integration-core-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:394) ~[spring-integration-core-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	(omitted)
Caused by: org.springframework.expression.spel.SpelEvaluationException: EL1008E: Property or field 'vehicleId' cannot be found on object of type 'byte[]' - maybe not public or not valid?
	at org.springframework.expression.spel.ast.PropertyOrFieldReference.readProperty(PropertyOrFieldReference.java:217) ~[spring-expression-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.expression.spel.ast.PropertyOrFieldReference.getValueInternal(PropertyOrFieldReference.java:104) ~[spring-expression-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.expression.spel.ast.PropertyOrFieldReference.access$000(PropertyOrFieldReference.java:51) ~[spring-expression-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.expression.spel.ast.PropertyOrFieldReference$AccessorLValue.getValue(PropertyOrFieldReference.java:407) ~[spring-expression-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.expression.spel.ast.CompoundExpression.getValueInternal(CompoundExpression.java:89) ~[spring-expression-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.expression.spel.ast.SpelNodeImpl.getTypedValue(SpelNodeImpl.java:116) ~[spring-expression-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.expression.spel.standard.SpelExpression.getValue(SpelExpression.java:371) ~[spring-expression-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.integration.aws.outbound.KinesisMessageHandler.buildPutRecordRequest(KinesisMessageHandler.java:187) ~[spring-integration-aws-2.0.0.RELEASE.jar:na]
	at org.springframework.integration.aws.outbound.KinesisMessageHandler.handleMessageToAws(KinesisMessageHandler.java:166) ~[spring-integration-aws-2.0.0.RELEASE.jar:na]
	at org.springframework.integration.aws.outbound.AbstractAwsMessageHandler.handleMessageInternal(AbstractAwsMessageHandler.java:177) ~[spring-integration-aws-2.0.0.RELEASE.jar:na]
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:165) ~[spring-integration-core-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	... 115 common frames omitted
```

As a workaround, I provided `AwsHeaders.PARTITION_KEY` to MessageHeaders but I think the behavior should be consistent with Spring Cloud Stream docs.

**Comment by amithkumarg** [comment]
Is this really resolved? I still face the same issue.

**Comment by artembilan** [comment]
The issue has been closed and resolved more than 3 years ago. So, or you use very old version of this project, or you face slightly different problem.
Any chances that you can raise a fresh GH issue with much more info?
Would be great if you can share something what can help us reproduce the problem and so on.

Thanks
